//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizUniformes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.EntradaAlmacen = new HashSet<EntradaAlmacen>();
            this.SalidaAlmacen = new HashSet<SalidaAlmacen>();
        }
    
        public int Id_Almacen { get; set; }
        public int Id_Articulo { get; set; }
        public int Id_TipoTalla { get; set; }
        public int Id_Talla { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int Existencias { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    
        public virtual Cat_Articulos Cat_Articulos { get; set; }
        public virtual Cat_Tallas Cat_Tallas { get; set; }
        public virtual Cat_TiposTallas Cat_TiposTallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntradaAlmacen> EntradaAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaAlmacen> SalidaAlmacen { get; set; }
    }
}
