//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizUniformes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Articulos()
        {
            this.Almacen = new HashSet<Almacen>();
        }
    
        public int Id_Articulo { get; set; }
        public string Articulo { get; set; }
        public string Descripcion { get; set; }
        public int Id_Estatus { get; set; }
        public int Id_TipoArticulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Almacen> Almacen { get; set; }
        public virtual Cat_Estatus Cat_Estatus { get; set; }
        public virtual Cat_TiposArticulos Cat_TiposArticulos { get; set; }
    }
}
