//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizUniformes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_TiposArticulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_TiposArticulos()
        {
            this.Cat_Articulos = new HashSet<Cat_Articulos>();
        }
    
        public int Id_TipoArticulo { get; set; }
        public string Tipo { get; set; }
        public int Id_Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Articulos> Cat_Articulos { get; set; }
        public virtual Cat_Estatus Cat_Estatus { get; set; }
    }
}
