//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizUniformes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SalidasAlmacen
    {
        public int Folio { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int Cantidad { get; set; }
        public string Articulo { get; set; }
        public string Descripcion { get; set; }
        public string Talla { get; set; }
        public string Nombre_Empleado { get; set; }
        public string Tipo { get; set; }
    }
}
